services:
  - type: web
    name: bossibilities
    env: static
    buildCommand: npm install
    staticPublishPath: ./
    envVars:
      - key: DOMAIN
        value: https://bossibilities.onrender.com
